### ISSUE TITLE
Upgrading from 2.3.0 to the latest 2.4 caused /dev/ttyUSB1 to disappear

### ISSUE THREAD

**Issue by hjnijlunsing** [intelwolf/p1monitor#10]
Situation:

Kubernetes with this spec snippet works:
```
 -     spec:                                                                                                                                                                                               
      containers:                                                                                                                                                                                       
      - env:                                                                                                                                                                                            
        - name: SOCAT_CONF                                                                                                        
          value: '"-T10 pty,link=/dev/ttyUSB1,rawer,group-late=dialout,mode=660 tcp:192.168.100.139:23,retry=forever,interval=30"'
        image: mclaassen/p1mon:2.3.0a    
```   

With this snippet it does not work (upgraded on april 15th):
```
  -     spec:                                                                                                                                                                                               
      containers:                                                                                                                                                                                       
      - env:                                                                                                                                                                                            
        - name: SOCAT_CONF                                                                                                        
          value: '"-T10 pty,link=/dev/ttyUSB1,rawer,group-late=dialout,mode=660 tcp:192.168.100.139:23,retry=forever,interval=30"'
        image: mclaassen/p1mon:2.3.0a   
```    

It seems that with the new version there is no /dev/ttyUSB1 with the same SOCAT_CONF
