### ISSUE TITLE
nginx init.d file missing

### ISSUE THREAD

**Issue by vascotenner** [intelwolf/p1monitor#20]
Ik heb de nieuweste versie geinstalleerd  (container id 0e0d3b8cb34c). Daarin wil nginx niet opstarten. Dat wordt geprobeerd via service nginx start, maar er bestaat geen /etc/init.d/nginx. Ik kon dit NIET oplossen door in de container via apt nginx en nging-common te purgen en opnieuw te installeren.

Als ik nginx opstart via nxing werkt de webserver wel.

**Comment by vascotenner** [comment]
Het lijkt erop dat geen enkele service wil draaien, ook service cron start geeft de melding dat deze service niet gevonden is. /etc/init.d/cron bestaat wel.

**Comment by intelwolf** [comment]
Even voor de duidelijkheid, welke image gebruik je? Of beter, waar heb je die vandaan? Er zijn nl. momenteel vele gebruikers van de actuele versies die je hier kunt vinden https://hub.docker.com/r/mclaassen/p1mon/tags

**Comment by vascotenner** [comment]
Ik heb eerste de oude versie gedeinstalleerd (zoals je me een jaar geleden al heb aanbevolen, maar ik was er nooit aan toe gekomen):
```docker rmi mclaassen/p1mon:latest ```
```docker-compose pull```

Mijn docker compose:
```
version: '3.8'
services:

  p1monitor:
    hostname: p1mon
    image: mclaassen/p1mon
    ports:
      - 81:80
    volumes:
      - ./alldata/data:/p1mon/data
      - ./alldata/usbdisk:/p1mon/mnt/usb
      - /var/log/p1monitor:/var/log/p1monitor
    tmpfs:
      - /run
      - /tmp
      - /p1mon/mnt/ramdisk
    devices:
      - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AQ68GHQH-if00-port0:/dev/ttyUSB0
    restart: unless-stopped
    #environment:
            #- DISABLECPUTEMP=true
            #- PROXYPATH=marcel
    expose:
      - "81"
    stop_grace_period: 30s
```
